### ISSUE TITLE
Decide a name and publish to NPM

### ISSUE THREAD

**Issue by sleexyz** [Originate/recouple#1]
We'll want to pick a name that will

1. easily convey what the value of this system is
2. give us adoption within the JS community
3. googleable

Also it should be available on NPM.

**Comment by ArcherWheeler** [comment]
**Resonate** is also available

**Comment by sleexyz** [comment]
# Synapsis
- NPM: available!
- Synapse is a junction between neurons
- Synapsis is the joining of two chromosome pairs during meiosis
